name: Continuous Integration

on:
  pull_request:
    branches: [main]
  push:
    branches: [main, dev]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true # if push again while a old build is running

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Check formatting (Prettier)
        run: npx prettier --check .

      - name: Lint code (ESLint)
        run: npm run lint

      - name: Run dependency security audit # should only run on [main]
        run: npm audit --audit-level=high # make two files ci_push.yml, ci_pull_request.yml


      # above runs 20 seconds
      # - name: Run unit tests # we should run only those (2000sec/month free)
      #   run: npm test:unit # or
      #   run: npm test:e2e
